version: '3.8'

services:
  admin_portal:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   no_cache: true
    restart: always
    image: registry.bill24.io/b24/admin-portal:beta-1.4
    ports:
      - '21018:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    # environment:
    #   - NODE_ENV=production
    #   # Enable experimental WebCrypto API support
    #   # - NODE_OPTIONS=--experimental-global-webcrypto
    #   - KEYCLOAK_URL=https://ids.oone.bz
    #   - KEYCLOAK_REALM=EP-Staging-ids
    #   - KEYCLOAK_CLIENT_ID=b24-admin-portal
    #   - KEYCLOAK_CLIENT_SECRET=yxPl1d1zSHTi2oeYkh6gpJApPQEMzlIw
    #   - KEYCLOAK_REDIRECT_URI=https://admin-staging.bill24.io/auth/keycloak/callback
    #   - APP_VERSION=1.0.0
