version: '3.8'

services:
  admin_portal:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   no_cache: true
    restart: always
    image: registry.bill24.io/b24/admin-portal:beta-1.0.11
    ports:
      - '21018:3000'
    # env_file:
    #   - .env
    environment:
      - NODE_ENV=production
      - NUXT_BASE_URL=https://admin-staging.bill24.io
      - NUXT_KEYCLOAK_URL=https://ids.oone.bz
      - NUXT_KEYCLOAK_REALM=EP-Staging-ids
      - NUXT_KEYCLOAK_CLIENT_ID=b24-admin-portal
      - NUXT_KEYCLOAK_CLIENT_SECRET=S2hKwXo11fG0foxDqUASk4rQBRpAM08K
      - NUXT_KEYCLOAK_COOKIE_MAX_AGE=86400
      - NUXT_KEYCLOAK_REDIRECT_URI=https://admin-staging.bill24.io/auth/keycloak/callback
      - NUXT_MANAGEMENT_API_URL=https://managementapi-staging.bill24.io
      - NUXT_PGW_MODULE_API_URL=http://172.16.81.141:22043
      - NUXT_SECURITY_API_URL=https://staging.bill24.io:22030
      - NUXT_PUBLIC_APP_VERSION=1.0.11
      - NUXT_PUBLIC_USER_PROFILE_URL=https://ids.oone.bz/realms/EP-Staging-ids/account
