version: '3.8'

services:
  admin_portal:
    image: registry.bill24.io/b24/admin-portal:beta-1.0
    ports:
      - "23055:3000"
    environment:
      - NODE_ENV=development
      # Enable experimental WebCrypto API support
      # - NODE_OPTIONS=--experimental-global-webcrypto
      - KEYCLOAK_URL=https://ids.oone.bz/reams/EP-Staging-ids
      - KEYCLOAK_REALM=EP-Staging-ids
      - KEYCLOAK_CLIENT_ID=b24-admin-portal
      - KEYCLOAK_CLIENT_SECRET=yxPl1d1zSHTi2oeYkh6gpJApPQEMzlIw
      - KEYCLOAK_REDIRECT_URI=0.0.0.0:23055/auth/keycloak/callback
      - APP_VERSION=1.0.0